"""authentication tables

Revision ID: f2c6b5036bba
Revises:
Create Date: 2024-10-06 20:33:46.962520

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "f2c6b5036bba"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
	# ### commands auto generated by Alembic - please adjust! ###
	op.create_table(
		"event",
		sa.Column("id", sa.Integer(), nullable=False),
		sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
		sa.Column("venue", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
		sa.Column("start_datetime", sa.DateTime(), nullable=False),
		sa.Column("category", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
		sa.Column("event_link", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
		sa.PrimaryKeyConstraint("id"),
	)
	op.create_table(
		"user",
		sa.Column("user_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
		sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
		sa.Column("password", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
		sa.Column("id", sa.Integer(), nullable=False),
		sa.Column("active", sa.Boolean(), nullable=False),
		sa.PrimaryKeyConstraint("id"),
	)
	op.create_table(
		"usereventsattended",
		sa.Column("user_id", sa.Integer(), nullable=False),
		sa.Column("event_id", sa.Integer(), nullable=False),
		sa.ForeignKeyConstraint(
			["event_id"],
			["event.id"],
		),
		sa.ForeignKeyConstraint(
			["user_id"],
			["user.id"],
		),
		sa.PrimaryKeyConstraint("user_id", "event_id"),
	)
	op.create_table(
		"usereventssaved",
		sa.Column("user_id", sa.Integer(), nullable=False),
		sa.Column("event_id", sa.Integer(), nullable=False),
		sa.ForeignKeyConstraint(
			["event_id"],
			["event.id"],
		),
		sa.ForeignKeyConstraint(
			["user_id"],
			["user.id"],
		),
		sa.PrimaryKeyConstraint("user_id", "event_id"),
	)
	# ### end Alembic commands ###


def downgrade() -> None:
	# ### commands auto generated by Alembic - please adjust! ###
	op.drop_table("usereventssaved")
	op.drop_table("usereventsattended")
	op.drop_table("user")
	op.drop_table("event")
	# ### end Alembic commands ###
